<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtimemodel" nsURI="http://runtimemetadata/1.0" nsPrefix="cz.cuni.mff.d3s.deeco.core.model.runtime">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eOperations name="findDefinition" lowerBound="1" eType="#//KnowledgeDefinition">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" upperBound="-1"
        eType="#//TopLevelKnowledgeDefinition" containment="true" eOpposite="#//TopLevelKnowledgeDefinition/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//Process" containment="true" eOpposite="#//Process/component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeDefinition" abstract="true"
      eSuperTypes="#//KnowledgeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StructuredKnowledgeType">
    <eLiterals name="KNOWLEDGE"/>
    <eLiterals name="LIST" value="1"/>
    <eLiterals name="MAP" value="2"/>
    <eLiterals name="UNSTRUCTURED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeType" abstract="true">
    <eOperations name="createFromRaw" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="rawValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="storeToRaw" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStructured" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWrapper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clazz" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//KnowledgeTypeOwner"
        eOpposite="#//KnowledgeTypeOwner/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//ParameterizedMethod #//Schedulable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/processes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduling" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Schedulable"
        eOpposite="#//Schedulable/scheduling"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredKnowledgeValueType" eSuperTypes="#//KnowledgeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//NestedKnowledgeDefinition" containment="true" eOpposite="#//NestedKnowledgeDefinition/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListValueType" eSuperTypes="#//ParametricKnowledgeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" lowerBound="1"
        eType="#//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapValueType" eSuperTypes="#//ParametricKnowledgeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyTypeParameter" lowerBound="1"
        eType="#//TypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueTypeParameter" lowerBound="1"
        eType="#//TypeParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnstructuredValueType" eSuperTypes="#//KnowledgeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eOperations name="update" lowerBound="1">
      <eParameters name="updateCommand" eType="#//ModelUpdateCommand"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembles" upperBound="-1"
        eType="#//Ensemble" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelUpdateCommand" abstract="true">
    <eOperations name="do">
      <eParameters name="model" eType="#//Model"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateKnowledgeStructureCommand" eSuperTypes="#//ModelUpdateCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddComponentCommand" eSuperTypes="#//ModelUpdateCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodParameter" eSuperTypes="#//KnowledgeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ParameterKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="knowledgePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//ParameterizedMethod"
        eOpposite="#//ParameterizedMethod/formalParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizedMethod" abstract="true">
    <eOperations name="invoke" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaringClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalParameters" upperBound="-1"
        eType="#//MethodParameter" containment="true" eOpposite="#//MethodParameter/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inParameters" upperBound="-1"
        eType="#//MethodParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outParameters" upperBound="-1"
        eType="#//MethodParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inOutParameters" upperBound="-1"
        eType="#//MethodParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterKind">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
    <eLiterals name="INOUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicScheduling" eSuperTypes="#//Scheduling">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulingType">
    <eLiterals name="PERIODIC"/>
    <eLiterals name="TRIGGERED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggeredScheduling" eSuperTypes="#//Scheduling">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" lowerBound="1"
        upperBound="-1" eType="#//Trigger" containment="true" eOpposite="#//Trigger/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//TriggeredScheduling"
        eOpposite="#//TriggeredScheduling/triggers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterChangedTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//MethodParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ensemble" eSuperTypes="#//Schedulable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="membership" lowerBound="1"
        eType="#//MembershipCondition" containment="true" eOpposite="#//MembershipCondition/ensemble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeExchange" lowerBound="1"
        eType="#//KnowledgeExchange" containment="true" eOpposite="#//KnowledgeExchange/ensemble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelKnowledgeDefinition" eSuperTypes="#//KnowledgeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/knowledge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedKnowledgeDefinition" eSuperTypes="#//KnowledgeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//StructuredKnowledgeValueType" eOpposite="#//StructuredKnowledgeValueType/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeReference" abstract="true"
      eSuperTypes="#//KnowledgeTypeOwner">
    <eOperations name="load" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="store" lowerBound="1">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MembershipCondition" eSuperTypes="#//ParameterizedMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensemble" lowerBound="1"
        eType="#//Ensemble" eOpposite="#//Ensemble/membership"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeExchange" eSuperTypes="#//ParameterizedMethod">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensemble" lowerBound="1"
        eType="#//Ensemble" eOpposite="#//Ensemble/knowledgeExchange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedulable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduling" lowerBound="1"
        eType="#//Scheduling" containment="true" eOpposite="#//Scheduling/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameter" eSuperTypes="#//KnowledgeTypeOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//ParametricKnowledgeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametricKnowledgeType" abstract="true"
      eSuperTypes="#//KnowledgeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeTypeOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//KnowledgeType"
        containment="true" eOpposite="#//KnowledgeType/owner"/>
  </eClassifiers>
</ecore:EPackage>
