<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime" nsURI="http://cz.cuni.mff.d3s.deeco.model.runtime/1.0"
    nsPrefix="cz.cuni.mff.d3s.deeco.model.runtime">
  <eClassifiers xsi:type="ecore:EClass" name="TimeTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wcet" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeChangeTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgePath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgePath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//PathNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNode" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Method" instanceClassName="java.lang.reflect.Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeField" eSuperTypes="#//PathNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeMapKey" eSuperTypes="#//PathNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeMetadata">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleDefinitions" upperBound="-1"
        eType="#//EnsembleDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstances" upperBound="-1"
        eType="#//ComponentInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="KnowledgeManager" instanceClassName="cz.cuni.mff.d3s.deeco.knowledge.KnowledgeManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentProcesses" upperBound="-1"
        eType="#//ComponentProcess" containment="true" eOpposite="#//ComponentProcess/componentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shadowKnowledgeManagerRegistry"
        lowerBound="1" eType="#//ShadowKnowledgeManagerRegistry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleControllers" upperBound="-1"
        eType="#//EnsembleController" containment="true" eOpposite="#//EnsembleController/componentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalData" upperBound="-1"
        eType="#//StringToObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemComponent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityRoles" upperBound="-1"
        eType="#//SecurityRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ratingsProcess" eType="#//RatingsProcess"
        containment="true" eOpposite="#//RatingsProcess/componentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnsembleDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membership" lowerBound="1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeExchange" lowerBound="1"
        eType="#//Exchange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationBoundary"
        eType="#//CommunicationBoundary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partitionedBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Invocable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exchange" eSuperTypes="#//Invocable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentProcess" eSuperTypes="#//Invocable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/componentProcesses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterKind">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
    <eLiterals name="INOUT" value="2"/>
    <eLiterals name="RATING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ParameterKind"
        defaultValueLiteral="INOUT" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgePath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericType" lowerBound="1"
        eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreKnowledgeCompromise"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ShadowKnowledgeManagerRegistry" instanceClassName="cz.cuni.mff.d3s.deeco.knowledge.ShadowKnowledgeManagerRegistry"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnsembleController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/ensembleControllers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleDefinition" lowerBound="1"
        eType="#//EnsembleDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeCoordinator" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeMember" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeComponentId" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CommunicationBoundary" instanceClassName="cz.cuni.mff.d3s.deeco.network.CommunicationBoundaryPredicate"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeSecurityTag" eSuperTypes="#//SecurityTag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1"
        eType="#//SecurityRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consistsOf" upperBound="-1"
        eType="#//SecurityRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//SecurityRoleArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aliasRole" eType="#//SecurityRole"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRoleArgument" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathSecurityRoleArgument" eSuperTypes="#//SecurityRoleArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgePath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextKind" lowerBound="1"
        eType="#//ContextKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlankSecurityRoleArgument" eSuperTypes="#//SecurityRoleArgument"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteSecurityRoleArgument" eSuperTypes="#//SecurityRoleArgument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RatingsManager" instanceClassName="cz.cuni.mff.d3s.deeco.integrity.RatingsManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="RatingsProcess" eSuperTypes="#//Invocable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/ratingsProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalKnowledgeTag" eSuperTypes="#//SecurityTag"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityTag"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ContextKind">
    <eLiterals name="LOCAL"/>
    <eLiterals name="SHADOW" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Type" instanceClassName="java.lang.reflect.Type"/>
</ecore:EPackage>
