<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime" nsURI="http://cz.cuni.mff.d3s.deeco.model.runtime/1.0"
    nsPrefix="cz.cuni.mff.d3s.deeco.model.runtime">
  <eClassifiers xsi:type="ecore:EClass" name="TimeTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeChangeTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgePath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgePath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//PathNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNode" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Method" instanceClassName="java.lang.reflect.Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeField" eSuperTypes="#//PathNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeMapKey" eSuperTypes="#//PathNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPath" lowerBound="1"
        eType="#//KnowledgePath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeMetadata">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleDefinitions" upperBound="-1"
        eType="#//EnsembleDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstances" upperBound="-1"
        eType="#//ComponentInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="KnowledgeManager" instanceClassName="cz.cuni.mff.d3s.deeco.knowledge.KnowledgeManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentProcesses" upperBound="-1"
        eType="#//ComponentProcess" containment="true" eOpposite="#//ComponentProcess/componentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shadowKnowledgeManagerRegistry"
        lowerBound="1" eType="#//ShadowKnowledgeManagerRegistry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleControllers" upperBound="-1"
        eType="#//EnsembleController" containment="true" eOpposite="#//EnsembleController/componentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalData" upperBound="-1"
        eType="#//StringToObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateSpaceModels" upperBound="-1"
        eType="#//StateSpaceModelDefinition" containment="true" eOpposite="#//StateSpaceModelDefinition/componentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//TransitionDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnsembleDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membership" lowerBound="1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeExchange" lowerBound="1"
        eType="#//Exchange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationBoundary"
        eType="#//CommunicationBoundary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Invocable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exchange" eSuperTypes="#//Invocable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentProcess" eSuperTypes="#//Invocable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/componentProcesses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//ModeState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirection">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
    <eLiterals name="INOUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgePath" eType="#//KnowledgePath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//ParameterDirection" defaultValueLiteral="INOUT" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ShadowKnowledgeManagerRegistry" instanceClassName="cz.cuni.mff.d3s.deeco.knowledge.ShadowKnowledgeManagerRegistry"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnsembleController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/ensembleControllers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensembleDefinition" lowerBound="1"
        eType="#//EnsembleDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeCoordinator" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeMember" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathNodeComponentId" eSuperTypes="#//PathNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToObjectMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CommunicationBoundary" instanceClassName="cz.cuni.mff.d3s.deeco.network.CommunicationBoundaryPredicate"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateSpaceModelDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="#//ModelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance" eOpposite="#//ComponentInstance/stateSpaceModels"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//TimeTrigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" lowerBound="1"
        upperBound="-1" eType="#//KnowledgePath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivationStates" upperBound="-1"
        eType="#//KnowledgePath"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelValue" lowerBound="1"
        eType="#//InaccurateValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ModelType" instanceClassName="cz.cuni.mff.d3s.deeco.model.runtime.stateflow.ModelInterface"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MetadataType">
    <eLiterals name="EMPTY"/>
    <eLiterals name="TS" value="1"/>
    <eLiterals name="MIN_BOUNDARY" value="2"/>
    <eLiterals name="MAX_BOUNDARY" value="3"/>
    <eLiterals name="INACCURACY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InaccurateValue" instanceClassName="cz.cuni.mff.d3s.deeco.model.runtime.stateflow.InaccuracyParamHolder"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeValueUnchangeTrigger" eSuperTypes="#//KnowledgeChangeTrigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparison" upperBound="-1"
        eType="#//ComparisonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meta" eType="#//MetadataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonType">
    <eLiterals name="EQUAL"/>
    <eLiterals name="EQUAL_LESS_THAN" value="1"/>
    <eLiterals name="EQUAL_MORE_THAN" value="2"/>
    <eLiterals name="LESS_THAN" value="3"/>
    <eLiterals name="MORE_THAN" value="4"/>
    <eLiterals name="EQUAL_STR" value="5"/>
    <eLiterals name="NOT_EQUAL" value="6"/>
    <eLiterals name="NOT_EQUAL_STR" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeValueChangeTrigger" eSuperTypes="#//KnowledgeChangeTrigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparison" upperBound="-1"
        eType="#//ComparisonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meta" eType="#//MetadataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromMode" eType="#//ComponentProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toMode" eType="#//ComponentProcess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//KnowledgeChangeTrigger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModeState">
    <eLiterals name="IDLE"/>
    <eLiterals name="REACHABLE" value="1"/>
    <eLiterals name="RUNNING" value="2"/>
  </eClassifiers>
</ecore:EPackage>
