/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s.jdeeco.edl;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EDLRuntimeModule extends cz.cuni.mff.d3s.jdeeco.edl.AbstractEDLRuntimeModule {
	@Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {		
        return EDLValueConverter.class;
    }
}
