/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_cuni_mff_d3s_deeco_simulation_OMNetSimulation */

#ifndef _Included_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
#define _Included_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    getCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    initializeHost
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeRegister
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSendPacket
  (JNIEnv *, jobject, jstring, jbyteArray, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeRun
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    callAt
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeCallAt
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String)Z
 */
JNIEXPORT jboolean JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeIsPositionInfoAvailable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String)Z
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionX
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String)Z
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionY
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String)Z
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionZ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSetPositionX
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSetPositionY
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSetPositionZ
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
