/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s.jdeeco.edl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EDLUiModule extends cz.cuni.mff.d3s.jdeeco.edl.ui.AbstractEDLUiModule {
	public EDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
