/**
 * Holds the classes responsible for parsing a string path into a list of {@link cz.cuni.mff.d3s.deeco.annotations.pathparser.PNode}s.
 * Most of the classes are automatically generated by JavaCC.
 * The ones that are NOT generated are:
 * <ul>
 * <li>{@link cz.cuni.mff.d3s.deeco.annotations.pathparser.ComponentIdentifier}</li>
 * <li>{@link cz.cuni.mff.d3s.deeco.annotations.pathparser.EEnsembleParty}</li>
 * <li>{@link cz.cuni.mff.d3s.deeco.annotations.pathparser.PathGrammar}</li>
 * <li>{@link cz.cuni.mff.d3s.deeco.annotations.pathparser.PNode}</li>
 * </ul>
 */
package cz.cuni.mff.d3s.deeco.annotations.pathparser;