/* Generated By:JavaCC: Do not edit this line. PathParserConstants.java */
package cz.cuni.mff.d3s.deeco.path.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 1;
  /** RegularExpression Id. */
  int LETTER = 2;
  /** RegularExpression Id. */
  int DIGIT = 3;
  /** RegularExpression Id. */
  int SEPARATOR = 4;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SEPARATOR>",
    "<OPEN>",
    "<CLOSE>",
  };

}
