<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adaptationarchitecture" nsURI="http://adaptationarchitecture/1.0"
    nsPrefix="adaptationarchitecture">
  <eAnnotations source="Michal you are so very cool"/>
  <eClassifiers xsi:type="ecore:EClass" name="Oracle">
    <eOperations name="isToBeScheduled">
      <eParameters name="job" eType="#//Job"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solver" lowerBound="1"
        eType="#//SATSolver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="irms" upperBound="-1" eType="#//Invariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SATSolver" abstract="true">
    <eOperations name="solve"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Runtime" instanceClassName="cz.cuni.mff.d3s.deeco.runtime.Runtime">
    <eOperations name="run" lowerBound="1"/>
    <eOperations name="shutdown" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oracle" lowerBound="1"
        eType="#//Oracle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler">
    <eOperations name="schedule">
      <eParameters name="job" eType="#//Job"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oracle" lowerBound="1"
        eType="#//Oracle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" instanceClassName="cz.cuni.mff.d3s.deeco.scheduling.Job"/>
  <eClassifiers xsi:type="ecore:EClass" name="SAT4JSolver" eSuperTypes="#//SATSolver"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRMPrimitive" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invariant" eSuperTypes="#//IRMPrimitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="O"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EEnum0"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//IRMPrimitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="2"
        upperBound="-1" eType="#//IRMPrimitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//Invariant #//Evaluable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessInvariant" eSuperTypes="#//Invariant #//Evaluable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentProcess" lowerBound="1"
        eType="#//ComponentProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeInvariant" eSuperTypes="#//Invariant #//Evaluable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ensemble" lowerBound="1"
        eType="#//Ensemble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentProcess" instanceClassName="cz.cuni.mff.d3s.deeco.runtime.model.ComponentProcess"
      eSuperTypes="#//ProcessInvariant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ensemble" instanceClassName="cz.cuni.mff.d3s.deeco.runtime.model.Ensemble"
      eSuperTypes="#//ExchangeInvariant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluable" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" instanceClassName="cz.cuni.mff.d3s.deeco.runtime.model.Component"/>
</ecore:EPackage>
