<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtimearchitecture" nsURI="http://runtimearchitecture/1.0"
    nsPrefix="runtimearchitecture">
  <eClassifiers xsi:type="ecore:EClass" name="EClass0"/>
  <eClassifiers xsi:type="ecore:EClass" name="Runtime">
    <eOperations name="deploy">
      <eParameters name="model" eType="#//RuntimeModel"/>
    </eOperations>
    <eOperations name="run"/>
    <eOperations name="shutdown"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Ensemble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//RuntimeModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" lowerBound="1"
        eType="#//Scheduler" containment="true" eOpposite="#//Scheduler/runtime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//ModelProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//RuntimeMetadata"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Runtime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ensemble"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler" abstract="true">
    <eOperations name="schedule">
      <eParameters name="job" eType="#//Job"/>
    </eOperations>
    <eOperations name="start"/>
    <eOperations name="stop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtime" lowerBound="1"
        eType="#//Runtime" eOpposite="#//Runtime/scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        eType="#//Executor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobQueue" upperBound="-1"
        eType="#//Job" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiThreadScheduler" eSuperTypes="#//Scheduler"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleThreadScheduler" eSuperTypes="#//Scheduler"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreetScheduler" eSuperTypes="#//Scheduler"/>
  <eClassifiers xsi:type="ecore:EClass" name="Executor">
    <eOperations name="execute" eType="#//Job">
      <eParameters name="job" eType="#//Job"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Job"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//KnowledgeManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference2" eType="#//PeriodicPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicPolicy" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SkipOnMisfire" eSuperTypes="#//PeriodicPolicy"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimultaneousExecution" eSuperTypes="#//PeriodicPolicy"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeManager" abstract="true">
    <eOperations name="getKnowledge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="session" eType="#//ISession"/>
    </eOperations>
    <eOperations name="getKnowledge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="expectedType" eType="#//KnowledgeType"/>
      <eParameters name="session" eType="#//ISession"/>
    </eOperations>
    <eOperations name="getKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="takeKnowledge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//KMException">
      <eParameters name="knowledge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="session" eType="#//ISession"/>
    </eOperations>
    <eOperations name="takeKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="alterKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="session" eType="#//ISession"/>
    </eOperations>
    <eOperations name="putKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="session" eType="#//ISession"/>
    </eOperations>
    <eOperations name="createSession" eType="#//ISession"/>
    <eOperations name="registerListener">
      <eParameters name="listener" eType="#//IKnowledgeChangeListener"/>
    </eOperations>
    <eOperations name="unregisterListener">
      <eParameters name="listener" eType="#//IKnowledgeChangeListener"/>
    </eOperations>
    <eOperations name="setListenerActive">
      <eParameters name="on" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="alterKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="putKnowledge" eExceptions="#//KMException">
      <eParameters name="knowledgePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelReference" lowerBound="1"
        eType="#//RuntimeModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicJob" eSuperTypes="#//Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggeredJob" eSuperTypes="#//Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeMetadata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentInstances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="components" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ensembles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealTimeScheduler" eSuperTypes="#//Scheduler"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteTimeScheduler" eSuperTypes="#//Scheduler"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISession" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KMException"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IKnowledgeChangeListener" interface="true"/>
</ecore:EPackage>
