<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture" nsURI="http://architecture/1.0" nsPrefix="architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Runtime" abstract="true" interface="true">
    <eOperations name="run"/>
    <eOperations name="shutdown"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" lowerBound="1"
        eType="#//Scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        eType="#//Executor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeManager" abstract="true" interface="true">
    <eOperations name="put">
      <eParameters name="changeset" eType="#//KnowledgeChangeset"/>
    </eOperations>
    <eOperations name="get" eType="#//Knowledge">
      <eParameters name="KnowledgeReference" eType="#//KnowledgeRef"/>
    </eOperations>
    <eOperations name="registerTrigger">
      <eParameters name="listener" eType="#//KnowledgeTriggerListener"/>
      <eParameters name="trigger" eType="#//KnowledgeTrigger"/>
    </eOperations>
    <eOperations name="unregisterTrigger">
      <eParameters name="trigger" eType="#//KnowledgeTrigger"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeners" upperBound="-1"
        eType="#//KnowledgeTriggerListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler" abstract="true" interface="true"
      eSuperTypes="#//TaskExecutionListener">
    <eOperations name="add">
      <eParameters name="task" eType="#//Task"/>
    </eOperations>
    <eOperations name="remove">
      <eParameters name="task" eType="#//Task"/>
    </eOperations>
    <eOperations name="start"/>
    <eOperations name="stop"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" interface="true"
      eSuperTypes="#//Schedulable #//Executable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Executor" abstract="true" interface="true">
    <eOperations name="execute">
      <eParameters name="task" eType="#//Executable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskExecutionListener" abstract="true"
      interface="true">
    <eOperations name="executionStarted">
      <eParameters name="task" eType="#//Executable"/>
    </eOperations>
    <eOperations name="executionFinished">
      <eParameters name="task" eType="#//Executable"/>
    </eOperations>
    <eOperations name="executionException">
      <eParameters name="task" eType="#//Executable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulerService" abstract="true" interface="true"
      eSuperTypes="#//Scheduler #//TaskExecutionListener #//KnowledgeTriggerListener">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        eType="#//Executor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutorService" abstract="true" interface="true"
      eSuperTypes="#//Executor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeners" upperBound="-1"
        eType="#//TaskExecutionListener"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeManager" lowerBound="1"
        eType="#//KnowledgeManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executables" upperBound="-1"
        eType="#//Executable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedulable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" changeable="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//KnowledgeTrigger" changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executable" abstract="true" interface="true">
    <eOperations name="execute" lowerBound="1" eType="#//ExecutionResult">
      <eParameters name="input" eType="#//Knowledge"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//KnowledgeRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionResult" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionException" abstract="true"
      interface="true" eSuperTypes="#//ExecutionResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeChangeset" abstract="true"
      interface="true" eSuperTypes="#//ExecutionResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeTriggerListener" abstract="true"
      interface="true">
    <eOperations name="triggered" lowerBound="1">
      <eParameters name="trigger" eType="#//KnowledgeTrigger"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeRef" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeTrigger" abstract="true" interface="true"/>
</ecore:EPackage>
