package cz.cuni.mff.d3s.jdeeco.network.l2;

/**
 * Interface for processing L2 packets generated by L1
 * 
 * This interface in entry point for data (wrapped as L2 packets) into Layer 2. Layer 1 is supposed to combine L1
 * fragments into L2 packets and then pass these via this interface to Layer 2.
 * 
 * @see Layer2
 * 
 * @author Vladimir Matena <matena@d3s.mff.cuni.cz>
 *
 */
public interface L1DataProcessor {
	/**
	 * Process data received from Layer 1 by Layer 2 strategies
	 * 
	 * This processes provided data wrapped in L2 packet by L2 strategies
	 * 
	 * @param packet
	 *            Layer 2 Packet to process
	 */
	public void processL2Packet(L2Packet packet);
}
