#! /bin/sh

omnetpp_root=`/d/omnetpp-4.3.1`
cd "$(dirname "$0")"
echo $omnetpp_root
export PATH=$omnetpp_root/bin:$PATH
export LD_LIBRARY_PATH=$omnetpp_root/lib:$LD_LIBRARY_PATH
export HOSTNAME
export HOST
make makefiles
cd src
make
