/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation */

#ifndef _Included_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
#define _Included_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeGetCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeRegister
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeRegister
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeSendPacket
 * Signature: (Ljava/lang/String;[BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSendPacket
  (JNIEnv *, jobject, jstring, jbyteArray, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeRun
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeRun
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeCallAt
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeCallAt
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeIsPositionInfoAvailable
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeIsPositionInfoAvailable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeGetPositionX
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionX
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeGetPositionY
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionY
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeGetPositionZ
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeGetPositionZ
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation
 * Method:    nativeSetPosition
 * Signature: (Ljava/lang/String;DDD)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_omnet_OMNetSimulation_nativeSetPosition
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
